name: online-counseling
description: Helm chart for the online counseling plattform
version: 0.0.1
apiVersion: v1
keywords:
  - online-counseling
sources:
  - https://github.com/Onlineberatung/onlineBeratung-kubernetes-ops.git
type: application
dependencies:
  - name: fluentbit
    version: 0.0.1
    condition: fluentbit.enabled
  - name: opensearch-cluster
    version: 0.0.1
    condition: opensearch-cluster.enabled
  - name: integritychecks
    version: 0.0.1
    condition: integritychecks.enabled
