service:
  enable: false
ingress:
  enable: false
input:
  http:
    enable: false
  onlineberatungTail:
    tag: kube.*
    bufferMaxSize: 3M
    path: /var/log/containers/*.log
    readFromHead: false
    multilineParser: docker, cri
    parser: cri
    refreshIntervalSeconds: 10
    memBufLimit: 3MB
    skipLongLines: true
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
output:
  opensearch: {}
  httpopensearch:
    logstashPrefix: "http"
filter:
  kubernetesOnlineberatung:
    enable: false
    include_record: false # Include the original record in the output for debugging
    kubernetes:
      labels: false
      annotations: false
parser:
  kubernetesOnlineberatungLoglevel:
    enable: false