{{- if not .Values.global.elkDisabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.enableCors }}"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.corsAllowHeaders }}"
  name: logstash
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  {{- if .Values.global.multitenancyWithSingleDomainEnabled }}
    - host: {{ .Values.global.domainName }}
  {{- else if .Values.global.multitenancyEnabled }}
    - host: "*.{{ .Values.global.domainName }}"
  {{- else }}
    - host: {{ .Values.global.domainName }}
  {{- end }}
      http:
        paths:
          - backend:
              service:
                name: logstash
                port:
                  number: 8080
            path: /service/logstash
            pathType: Prefix
{{- end }}