{{- if and .Values.parser.systemdjson.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: systemd-json
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  json:
    timeFormat: "%Y-%m-%dT%H:%M:%S.%L"
    timeKeep: true
    timeKey: time
{{- end }}
