{{- if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    {{- if .Values.ingress.enableCors }}
    nginx.ingress.kubernetes.io/enable-cors: {{ .Values.ingress.enableCors | quote }}
    {{- end }}
    {{- if .Values.ingress.corsAllowOrigin }}
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.ingress.corsAllowOrigin | quote }}
    {{- end }}
    {{- if .Values.ingress.corsAllowHeaders }}
    nginx.ingress.kubernetes.io/cors-allow-headers: {{ .Values.ingress.corsAllowHeaders | quote }}
    {{- end }}
  name: fluentbit-ingress-http
  namespace: {{ .Values.namespace | default "default" }}
spec:
  ingressClassName: nginx
  rules:
  {{- if and .Values.global.multitenancyWithSingleDomainEnabled .Values.global.multitenancyEnabled }}
    - host: "*.{{ .Values.global.domainName }}"
  {{- else }}
    - host: {{ .Values.global.domainName }}
  {{- end }}
      http:
        paths:
          - backend:
              service:
                name: fluentbit-http-service
                port:
                  number: {{ .Values.input.http.port | default 8888 }}
            path: /service/logstash
            pathType: Prefix
{{- end }}