{{- if .Values.output.opensearch -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fluentd-output-httpopensearch
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: http.*
  opensearch:
{{ toYaml .Values.output.opensearch | indent 4}}
{{ toYaml .Values.output.httpopensearch | indent 4}}
{{- end }}
