apiVersion: v1
kind: Secret
metadata:
  name: integritychecks-{{ .Release.Name }}-secret
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: app
type: Opaque
data:
  TEAMS_WEBHOOK_URL: {{ .Values.teams.webhookUrl | default "" | b64enc | quote }}
  {{- range $path, $config := .Values.mysql -}}
    {{- if and $config (eq $path "password") -}}
      {{- printf "MYSQL_%s" (upper $path) | nindent 2 }}: {{ $config | b64enc | quote -}}
    {{- end -}}
  {{- end -}}
  {{- range $path, $config := .Values.mongodb -}}
    {{- if and $config (eq $path "password") -}}
      {{- printf "MONGODB_%s" (upper $path) | nindent 2 }}: {{ $config | b64enc | quote -}}
    {{- end -}}
  {{- end -}}
  {{- range $path, $config := .Values.keycloak -}}
    {{- if and $config (eq $path "password") -}}
      {{- printf "KEYCLOAK_%s" (upper $path) | nindent 2 }}: {{ $config | b64enc | quote -}}
    {{- end -}}
  {{- end -}}
  {{- range $path, $config := .Values.opensearch -}}
    {{- if and $config (eq $path "password") -}}
      {{- printf "OPENSEARCH_%s" (upper $path) | nindent 2 }}: {{ $config | b64enc | quote -}}
    {{- end -}}
  {{- end -}}
