apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: {{ .Values.serviceName | default "opensearch" }}-cluster
  namespace: {{ .Values.namespace | default "default" }}
spec:
  general:
    version: 2.5.0
    httpPort: {{ .Values.httpPort }}
    vendor: opensearch
    setVMMaxMapCount: true
    serviceName: {{ .Values.serviceName | default "opensearch" }}
    pluginsList: ["repository-s3"," https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.5.0.0/prometheus-exporter-2.5.0.0.zip"]
  dashboards:
    version: {{ .Values.dashboard.version }}
    enable: {{ .Values.dashboard.enabled }}
    replicas: {{ .Values.dashboard.replicas }}
    {{ if and .Values.username .Values.password }}
    opensearchCredentialsSecret:
      name: {{ .Values.serviceName | default "opensearch" }}-cluster-secret
    {{ end }}
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    additionalConfig:
      opensearch_security.multitenancy.enabled: "false"
  confMgmt:
    smartScaler: true
  {{ if and .Values.username .Values.password }}
  security:
    config:
      adminCredentialsSecret:
        name: {{ .Values.serviceName | default "opensearch" }}-cluster-secret
      {{ if .Values.passwordHash }}
      securityConfigSecret:
        name: {{ .Values.serviceName | default "opensearch" }}-securityconfig-secret
      {{ end }}
  {{ end }}
  nodePools:
    - component: masters
      replicas: {{ .Values.masters.replicas }}
      diskSize: "30Gi"
      NodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "3Gi"
          cpu: "1000m"
      roles:
        - "cluster_manager"
        - "data"
    - component: nodes
      replicas: {{ .Values.nodes.replicas }}
      diskSize: "30Gi"
      NodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "3Gi"
          cpu: "1000m"
      roles:
        - "data"
    - component: coordinators
      replicas: {{ .Values.coordinators.replicas }}
      diskSize: "30Gi"
      NodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "3Gi"
          cpu: "1000m"
      roles:
        - "ingest"