{{- if and .Values.username .Values.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName | default "opensearch" }}-cluster-secret
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: app
type: Opaque
data:
  username: {{ .Values.username | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
{{- end }}