{{- if .Values.global.exposeAdminer }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - backend:
              service:
                name: adminer
                port:
                  number: 8080
            path: /mariadb/(.*)
            pathType: Prefix
{{- end}}