httpPort: 9200
version: 2.5.0
dashboard:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"
nodes:
  replicas: 0
masters:
  replicas: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "500m"
coordinators:
  replicas: 0
# To override the password you can use the following attributes:
username: admin
password: admin
# Generate a password hash using the following page:
# https://bcrypt-generator.com/
#passwordHash: $2a$12$lTsgwZkhRChLyaAvCw/TpORLe2E.DtfX7nVTV96HCgkbTEh5/Ai82
