apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: backup
roleRef:
  kind: ClusterRole
  name: backup-cluster-reader
  apiGroup: rbac.authorization.k8s.io