{{- if .Values.enableBackup }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-secret-{{ .Release.Name }}-env
  namespace: backup
  labels:
    app: app
type: Opaque
data:
  MYSQL_PWD: {{ .Values.mysqlRootPassword | b64enc | quote }}
  DATABASES: {{ .Values.backupDatabases | b64enc | quote }}
  {{- if .Values.global.useExternalMariaDb }}
  DATABASE_HOST: {{ .Values.global.mariaDbHost | b64enc | quote }}
  {{- else }}
  DATABASE_HOST: {{ .Values.backupDatabaseHost | b64enc | quote }}
  {{- end }}
  DATABASE_USER: {{ .Values.backupDatabaseUser | b64enc | quote }}
  BUCKET_NAME: {{ .Values.backupBucketName | b64enc | quote }}
  BUCKET_ACCESS_KEY: {{ .Values.backupBucketAccessKey | b64enc | quote }}
  BUCKET_SECRET_KEY: {{ .Values.backupBucketSecretKey | b64enc | quote }}
  MONGODB_ADMIN: {{ .Values.backupMongoDBAdmin | b64enc | quote }}
  MONGODB_ADMIN_PASS: {{ .Values.backupMongoDBAdminPass | b64enc | quote }}
  MONGODB_HOST: {{ .Values.backupMongoDBHost | b64enc | quote }}
  GSCLOUD_USERID: {{ .Values.backupGsCloudUserUUID | b64enc | quote }}
  GSCLOUD_TOKEN: {{ .Values.backupGsCloudApiToken | b64enc | quote }}
  GSCLOUD_CLUSTER_ID: {{ .Values.backupGsCloudClusterId | b64enc | quote }}
  NAMESPACE: {{ .Values.backupNamespace | b64enc | quote }}
  POSTGRESQL_HOST: {{ .Values.backupPostgresHost | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.backupPostgresPassword | b64enc | quote }}
  BUDIBASE_ADMIN: {{ .Values.backupBudibaseAdmin | b64enc | quote }}
  BUDIBASE_ADMIN_PASS: {{ .Values.backupBudibaseAdminPass | b64enc | quote }}
  BACKUP_ENCRYPTION_KEY: {{ .Values.backupEncryptionKey | b64enc | quote }}
  BACKUPS_TO_KEEP: {{ int .Values.backupsToKeep | toString | b64enc | quote }}
{{- end }}
