{{- if .Values.enableBackup }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script-{{ .Release.Name }}-configmap
  namespace: backup
data:
  {{- (.Files.Glob "resources/backup.sh").AsConfig | nindent 2 }}
{{-end }}
